### ISSUE TITLE
Use the base64 encoding for &[u8

### ISSUE THREAD

**Issue by solarau** [marshallpierce/base64-serde#11]
I'm newbie rust user.
I want to use a serializing function of base64 encoding for &[u8].

Once I try to use a base64-serde module with checking with
https://github.com/serde-rs/serde/issues/661, however I cannot handle this module with
for &[u8] field member.

Could you give me any advice?

**Comment by marshallpierce** [comment]
I've pushed a test https://github.com/marshallpierce/base64-serde/commit/67eeacd7b2e7031fe81211823b756743cca427cb showing how to serialize a `&[u8]`.

**Comment by marshallpierce** [comment]
Re-open if you're having problems.

**Comment by solarau** [comment]
Thanks you, it works for me!
I am sorry that I also expect to work a deserialize function as serialize it.

I hope it works like '#[serde(borrow)]' field attributes in serde.
It does not care about overhead of [u8] copy processing, at this point.

As far as I examined, I am not sure that it can be two approach to achieve that.
1. Implement a deserializer and a visitor for &[u8] like serde_bytes.
   I could not arrange how to implement it yet.
3. Use "From" or "Into" trait and implement them for &[u8].
   However I cannot handle it like From or Into for Vec<u8> because of lifetime.

Although I am in process of trial and error, I think this thread is not
appropriate.
Thanks your reply and close it .

**Comment by marshallpierce** [comment]
OK, feel free to open a PR if you get something figured out that you think would be generally useful.
