### ISSUE TITLE
Making file optional

### ISSUE THREAD

**Issue by leizzer** [marshallpierce/base64-serde#14]
I'm trying to make a file optional and I'm getting errors while deserializing.

```
#[derive(Deserialize)]
pub struct UpdateParams {
    #[serde(with = "Base64Standard")]
    pub file: Option<Vec<u8>>
}
```

```
error[E0308]: mismatched types
  --> src/actions/cards.rs:47:10
   |
47 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^
   |          |
   |          expected enum `std::option::Option`, found struct `std::vec::Vec`
   |          in this macro invocation
   |
   = note: expected type `std::option::Option<std::vec::Vec<_>>`
              found type `std::vec::Vec<_>`
```

PS: Thank you for this easy to use package :)

**Comment by marshallpierce** [comment]
Interesting... could you make a branch with a test case that reproduces the issue? I wonder if maybe it's just something a newer version of serde would solve.

**Comment by leizzer** [comment]
I was creating a small project and I don't get the same error.
I'll keep digging tomorrow and return to you

**Comment by leizzer** [comment]
Solved it by removin`Option` and using `#[serde(default)]` instead.
I don't like that solution because it populates `file` with an empty string, but is the only solution that I could find.

This is a simple example of what I was doing.
https://github.com/leizzer/base64-serde-test
