### ISSUE TITLE
Consider using an SPDX-recognized license

### ISSUE THREAD

**Issue by GeorgeHahn** [marshallpierce/base64-serde#20]
First off, thanks for the great piece of code!

I would like to use this crate in a repo with [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) rules in place, but the tool will not accept non-SPDX licenses. I'm not too familiar with this license, but it sounds like it's pretty similar to Apache-2.0. Would it be possible to license this crate as Apache-2.0?

**Comment by marshallpierce** [comment]
I'm happy to dual license if it makes the lawyers happy (sigh), but this license is less restrictive than Apache, so from a legal perspective you're already set if Apache 2 is good enough.

**Comment by GeorgeHahn** [comment]
That would be fantastic - Apache 2 would make the tooling & legal sides of this much simpler. Thank you!

**Comment by marshallpierce** [comment]
0.5.1 released with license = "Apache 2.0". LMK if that doesn't fix it.
