### ISSUE TITLE
Crate has not been upgraded to base64 0.20.x

### ISSUE THREAD

**Issue by mseele** [marshallpierce/base64-serde#25]
For this reason, the test (what I used as example) is still referring to `use base64::STANDARD` which is gone in base64 0.20.x

**Comment by marshallpierce** [comment]
Oops. I'll take care of it.

**Comment by marshallpierce** [comment]
0.7.0-beta.1 released, using base64-0.21.0-beta.1. (Beta because there might be some API changes; it works fine.)
